import {getPlatformAdminDashboard} from "./data"; import {getAdminModuleStats} from "./modules-data"; import {AdminShell,AdminStats,AdminOwnerCard,OrganizationsModule,PlansModule,PaymentsModule,UsersModule,SubscriptionsModule,IntegrationsModule,AiModule,AuditModule} from "./_components";
export default async function AdminPage(){const [dashboard,stats]=await Promise.all([getPlatformAdminDashboard(),getAdminModuleStats()]);return <AdminShell>
<style>{`@media (max-width: 720px){.admin-hero-grid{grid-template-columns:1fr!important}.admin-module-grid{grid-template-columns:1fr!important}.admin-content-grid{grid-template-columns:1fr!important}.admin-hero-card{padding:18px!important}.admin-hero-title{font-size:28px!important;line-height:1.08!important}.admin-hero-status{min-width:0!important;width:100%}}`}</style>
<section className="admin-hero-grid" style={{display:"grid",gridTemplateColumns:"minmax(0,1.7fr) minmax(0,.8fr)",gap:14}}>
 <div className="admin-hero-card" style={{padding:22,borderRadius:20,border:"1px solid rgba(126,145,190,.18)",background:"linear-gradient(135deg,rgba(19,25,43,.88),rgba(12,16,27,.92))"}}>
  <div style={{fontSize:11,letterSpacing:".16em",color:"#8492ff"}}>AI OPERATIONS LAYER</div><h2 className="admin-hero-title" style={{fontSize:30,margin:"8px 0"}}>Платформа управляется как единая система</h2>
  <p style={{color:"#a5afc2",lineHeight:1.6,maxWidth:760,marginBottom:16}}>Данные, роли, подписки, интеграции, API и бизнес-процессы объединены в одном операционном контуре. Следующий уровень — AI-команды, которые выполняют действия непосредственно в системе.</p>
  <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{["AI Assistant","Automation Engine","Universal Builder","API Core"].map(x=><span key={x} style={{padding:"7px 10px",borderRadius:999,border:"1px solid rgba(126,145,190,.2)",background:"rgba(255,255,255,.03)",color:"#c3cbe0",fontSize:12}}>{x}</span>)}</div>
 </div>
 <div className="admin-hero-card admin-hero-status" style={{padding:22,borderRadius:20,border:"1px solid rgba(0,220,190,.18)",background:"linear-gradient(135deg,rgba(7,42,43,.55),rgba(10,19,28,.9))"}}>
  <div style={{fontSize:11,letterSpacing:".16em",color:"#58dbc8"}}>AI CORE</div><div style={{fontSize:25,fontWeight:750,marginTop:8}}>● Online</div><p style={{color:"#9fb9b8",fontSize:13,lineHeight:1.5}}>Центральный AI-контур готов к маршрутизации моделей и инструментальным действиям.</p><a href="/admin/ai" style={{color:"#70e4d2",fontSize:13}}>Открыть AI Core →</a>
 </div>
</section>
<AdminStats organizations={dashboard.organizations} plans={dashboard.plans}/><AdminOwnerCard ownerUserId={dashboard.owner_user_id}/>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12,marginTop:24}}>{[["Пользователи",stats.memberships,"/admin/users","◉"],["Подписки",stats.subscriptions,"/admin/subscriptions","↻"],["Интеграции",stats.integrations,"/admin/integrations","◇"],["AI-запуски",stats.ai_runs,"/admin/ai","✦"],["Аудит",stats.audit_logs,"/admin/audit","≡"]].map(([label,value,href,icon])=><a key={String(href)} href={String(href)} style={{padding:18,border:"1px solid rgba(126,145,190,.17)",borderRadius:17,background:"rgba(16,21,34,.84)",color:"#fff",textDecoration:"none"}}><div style={{display:"flex",justifyContent:"space-between",color:"#8793aa",fontSize:12}}><span>{String(label)}</span><span style={{fontSize:18,color:"#7f8cff"}}>{String(icon)}</span></div><strong style={{display:"block",fontSize:28,marginTop:9}}>{String(value)}</strong><span style={{color:"#65718a",fontSize:12}}>Открыть модуль →</span></a>)}</section>
<section className="admin-content-grid" style={{marginTop:30,display:"grid",gap:18}}><OrganizationsModule organizations={dashboard.organizations}/><UsersModule stats={stats}/><PlansModule plans={dashboard.plans}/><SubscriptionsModule stats={stats}/><PaymentsModule payments={dashboard.payments}/><IntegrationsModule stats={stats}/><AiModule stats={stats}/><AuditModule stats={stats}/></section>
</AdminShell>}