"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
type Field={id:string;key:string;name:string;field_type:string;required:boolean;position:number;config?:any};
type Status={id:string;key:string;name:string;position:number;is_default:boolean;is_terminal:boolean;config:any};
type Entity={id:string;key:string;name:string;description:string|null;config?:any};
const input={padding:11,borderRadius:10,border:"1px solid #303747",background:"#121620",color:"white",width:"100%",boxSizing:"border-box" as const};
const types=["text","long_text","number","date","datetime","boolean","money","email","phone","select","relation"];
export function EntityEditor({entity,fields,statuses,entities,workspaceId}:{entity:Entity;fields:Field[];statuses:Status[];entities:Entity[];workspaceId:string}) {
 const router=useRouter(); const [name,setName]=useState(entity.name); const [relationKey,setRelationKey]=useState(""); const [relationName,setRelationName]=useState(""); const [relationTarget,setRelationTarget]=useState(""); const [description,setDescription]=useState(entity.description??""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function call(body:any){const r=await fetch("/api/builder/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Ошибка");return d}
 async function save(){setBusy(true);setError("");try{await call({action:"update_entity",entityId:entity.id,name,description,config:entity.config??{}});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
 async function saveField(f:Partial<Field>){setBusy(true);setError("");try{await call({action:"upsert_field",entityId:entity.id,fieldId:f.id??null,key:f.key,name:f.name,fieldType:f.field_type,required:!!f.required,position:f.position??0,config:f.config??{}});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
 async function removeField(id:string){if(!confirm("Удалить поле?"))return;setBusy(true);try{await call({action:"delete_field",fieldId:id});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
 async function saveStatus(s:Partial<Status>){setBusy(true);setError("");try{await call({action:"upsert_status",entityId:entity.id,statusId:s.id??null,key:s.key,name:s.name,position:s.position??0,isDefault:!!s.is_default,isTerminal:!!s.is_terminal,config:s.config??{}});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
 async function removeStatus(id:string){if(!confirm("Удалить статус?"))return;setBusy(true);try{await call({action:"delete_status",statusId:id});router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
 return <div style={{display:"grid",gap:18}}><header><div style={{color:"#8f9ab0",fontSize:12,letterSpacing:".12em"}}>BUILDER · {entity.key}</div><h1 style={{margin:"8px 0"}}>{entity.name}</h1><p style={{color:"#aab2c3"}}>Сущность — базовый строительный блок универсальной системы.</p></header>
 <section style={{padding:20,border:"1px solid #303747",borderRadius:16}}><h2>Основные настройки</h2><div style={{display:"grid",gap:10,maxWidth:700}}><input style={input} value={name} onChange={e=>setName(e.target.value)}/><textarea style={{...input,minHeight:90}} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Описание"/><button disabled={busy} onClick={save} style={{width:"fit-content",padding:"10px 14px",borderRadius:10}}>Сохранить</button></div></section>
 <section style={{padding:20,border:"1px solid #303747",borderRadius:16}}><h2>Поля</h2><div style={{display:"grid",gap:10}}>{fields.map(f=><div key={f.id} style={{display:"grid",gridTemplateColumns:"1fr 1fr 150px auto auto",gap:8,alignItems:"center"}}><input style={input} value={f.key} onChange={e=>{f.key=e.target.value}}/><input style={input} value={f.name} onChange={e=>{f.name=e.target.value}}/><select style={input} value={f.field_type} onChange={e=>{f.field_type=e.target.value}}>{types.map(t=><option key={t}>{t}</option>)}</select><button onClick={()=>saveField(f)}>Сохранить</button><button onClick={()=>removeField(f.id)}>Удалить</button></div>)}<button onClick={()=>saveField({key:"new_field_"+(fields.length+1),name:"Новое поле",field_type:"text",required:false,position:fields.length})}>+ Добавить поле</button></div></section>
 <section style={{padding:20,border:"1px solid #303747",borderRadius:16}}><h2>Статусы и воронка</h2><div style={{display:"grid",gap:10}}>{statuses.map(s=><div key={s.id} style={{display:"grid",gridTemplateColumns:"1fr 1fr 90px auto auto",gap:8,alignItems:"center"}}><input style={input} value={s.key} onChange={e=>{s.key=e.target.value}}/><input style={input} value={s.name} onChange={e=>{s.name=e.target.value}}/><input style={input} type="number" value={s.position} onChange={e=>{s.position=Number(e.target.value)}}/><button onClick={()=>saveStatus(s)}>Сохранить</button><button onClick={()=>removeStatus(s.id)}>Удалить</button></div>)}<button onClick={()=>saveStatus({key:"new_status_"+(statuses.length+1),name:"Новый статус",position:statuses.length,is_default:statuses.length===0,is_terminal:false})}>+ Добавить статус</button></div></section>
 <section style={{padding:20,border:"1px solid #303747",borderRadius:16}}><h2>Связи</h2><p style={{color:"#aab2c3"}}>Типизированная связь между сущностями.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr auto",gap:8}}><input style={input} placeholder="Ключ" value={relationKey} onChange={e=>setRelationKey(e.target.value)}/><input style={input} placeholder="Название" value={relationName} onChange={e=>setRelationName(e.target.value)}/><select style={input} value={relationTarget} onChange={e=>setRelationTarget(e.target.value)}><option value="">Целевая сущность</option>{entities.filter(x=>x.id!==entity.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button disabled={busy||!relationKey||!relationName||!relationTarget} onClick={async()=>{setBusy(true);setError("");try{await call({action:"create_relation",workspaceId,fromEntityId:entity.id,toEntityId:relationTarget,key:relationKey,name:relationName,relationType:"many_to_one"});setRelationKey("");setRelationName("");setRelationTarget("");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}}>Создать</button></div><div style={{color:"#8f9ab0",fontSize:13,marginTop:8}}>Сущностей в workspace: {entities.length}</div></section>
 {error&&<div style={{color:"#ffb4b4"}}>{error}</div>}</div>
}