"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
type Field={id:string;key:string;name:string;field_type:string;required:boolean;config?:any};
type Status={id:string;key:string;name:string};
type Entity={id:string;key:string;name:string};
type Relation={id:string;key:string;name:string;relation_type:string;from_entity_id:string;to_entity_id:string};
type RecordItem={id:string;status_id:string|null;data:Record<string,any>;created_at:string;updated_at:string};
type Link={id:string;from_record_id:string;to_record_id:string;relation_type:string;metadata?:any;created_at:string};
function inputType(t:string){return t==="number"||t==="money"||t==="currency"?"number":t==="date"?"date":t==="datetime"?"datetime-local":t==="email"?"email":t==="phone"?"tel":"text"}
function normalizeValue(f:Field,v:any){if(v===undefined||v===null)return "";if(f.field_type==="datetime")return String(v).slice(0,16);return v}
export function RecordPanel({workspaceId,entityId,fields,statuses,initialRecords,relations,entities}:{workspaceId:string;entityId:string;fields:Field[];statuses:Status[];initialRecords:RecordItem[];relations:Relation[];entities:Entity[]}){
 const router=useRouter(); const [data,setData]=useState<Record<string,any>>({}); const [statusId,setStatusId]=useState(""); const [editing,setEditing]=useState<RecordItem|null>(null); const [selected,setSelected]=useState<RecordItem|null>(null); const [links,setLinks]=useState<Link[]>([]); const [targetId,setTargetId]=useState(""); const [relationId,setRelationId]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [filterStatus,setFilterStatus]=useState(""); const [sortKey,setSortKey]=useState("updated"); const [desc,setDesc]=useState(true);
 function setValue(key:string,value:any){setData(v=>({...v,[key]:value}))}
 function startEdit(r:RecordItem){setEditing(r);setSelected(null);setData({...r.data});setStatusId(r.status_id??"");setError("");window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
 function reset(){setEditing(null);setData({});setStatusId("");setError("")}
 async function save(){setBusy(true);setError("");try{for(const f of fields)if(f.required&&(data[f.key]===undefined||data[f.key]===""))throw new Error("Заполните обязательное поле: "+f.name);const r=await fetch("/api/builder/record",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{recordId:editing.id,data,statusId:statusId||null}:{workspaceId,entityId,data,statusId:statusId||null})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Не удалось сохранить запись");reset();router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка сохранения")}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm("Удалить эту запись? Это действие нельзя отменить."))return;setBusy(true);setError("");try{const r=await fetch("/api/builder/record?id="+encodeURIComponent(id)+"&workspaceId="+encodeURIComponent(workspaceId),{method:"DELETE"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Не удалось удалить запись");if(selected?.id===id)setSelected(null);if(editing?.id===id)reset();router.refresh()}catch(e){setError(e instanceof Error?e.message:"Ошибка удаления")}finally{setBusy(false)}}
 async function openDetails(r:RecordItem){setSelected(r);setError("");setTargetId("");setRelationId("");try{const x=await fetch("/api/builder/relation?workspaceId="+encodeURIComponent(workspaceId)+"&recordId="+encodeURIComponent(r.id));const d=await x.json().catch(()=>[]);if(x.ok)setLinks(d)}catch{}}
 async function addLink(){if(!selected||!targetId||!relationId)return;setBusy(true);setError("");try{const rd=relations.find(x=>x.id===relationId);const r=await fetch("/api/builder/relation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId,fromRecordId:selected.id,toRecordId:targetId,relationType:rd?.key||"related",metadata:{relation_definition_id:relationId}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Не удалось создать связь");setLinks(v=>[d,...v]);setTargetId("")}catch(e){setError(e instanceof Error?e.message:"Ошибка связи")}finally{setBusy(false)}}
 async function removeLink(id:string){setBusy(true);try{const r=await fetch("/api/builder/relation?id="+encodeURIComponent(id)+"&workspaceId="+encodeURIComponent(workspaceId),{method:"DELETE"});if(!r.ok)throw new Error("Не удалось удалить связь");setLinks(v=>v.filter(x=>x.id!==id))}catch(e){setError(e instanceof Error?e.message:"Ошибка связи")}finally{setBusy(false)}}
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return initialRecords.filter(r=>{if(filterStatus&&r.status_id!==filterStatus)return false;if(!q)return true;return fields.some(f=>String(r.data?.[f.key]??"").toLowerCase().includes(q))}).sort((a,b)=>{let av:any=sortKey==="updated"?a.updated_at:sortKey==="created"?a.created_at:(a.data?.[sortKey]??"");let bv:any=sortKey==="updated"?b.updated_at:sortKey==="created"?b.created_at:(b.data?.[sortKey]??"");if(typeof av==="string")av=av.toLowerCase();if(typeof bv==="string")bv=bv.toLowerCase();const c=av>bv?1:av<bv?-1:0;return desc?-c:c})},[initialRecords,search,filterStatus,sortKey,desc,fields]);
 const nameOf=(id:string)=>{const r=initialRecords.find(x=>x.id===id);return r?(fields[0]?String(r.data?.[fields[0].key]??"Без названия"):"Запись"):id.slice(0,8)+"…"};
 return <section style={{display:"grid",gap:18,marginTop:18}}>
  {selected&&<div style={{padding:20,border:"1px solid #4b5870",borderRadius:16,background:"#101722"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{color:"#8f9ab0",fontSize:12}}>КАРТОЧКА ЗАПИСИ</div><h2 style={{margin:"6px 0"}}>{fields[0]?String(selected.data?.[fields[0].key]??"Без названия"):"Запись"}</h2><div style={{color:"#737e94",fontSize:12}}>Создана: {new Date(selected.created_at).toLocaleString("ru-RU")} · Изменена: {new Date(selected.updated_at).toLocaleString("ru-RU")}</div></div><button style={secondary} onClick={()=>setSelected(null)}>Закрыть</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginTop:16}}>{fields.map(f=><div key={f.id} style={{padding:10,border:"1px solid #303747",borderRadius:10}}><div style={{fontSize:12,color:"#737e94"}}>{f.name}</div><div style={{marginTop:4}}>{f.field_type==="boolean"?(selected.data?.[f.key]?"Да":"Нет"):String(selected.data?.[f.key]??"—")}</div></div>)}</div>
   <div style={{marginTop:18,borderTop:"1px solid #303747",paddingTop:16}}><h3 style={{margin:"0 0 10px"}}>Связанные записи</h3>{relations.length===0?<div style={{color:"#8f9ab0"}}>Для этой сущности пока нет настроенных связей.</div>:<><div style={{display:"grid",gridTemplateColumns:"minmax(180px,1fr) minmax(180px,1fr) auto",gap:8}}><select style={input} value={relationId} onChange={e=>setRelationId(e.target.value)}><option value="">Тип связи</option>{relations.map(r=><option key={r.id} value={r.id}>{r.name} · {entities.find(e=>e.id===(r.from_entity_id===entityId?r.to_entity_id:r.from_entity_id))?.name??"объект"}</option>)}</select><select style={input} value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Выберите запись</option>{initialRecords.filter(r=>r.id!==selected.id).map(r=><option key={r.id} value={r.id}>{nameOf(r.id)}</option>)}</select><button disabled={busy||!relationId||!targetId} onClick={addLink} style={button}>Связать</button></div><div style={{display:"grid",gap:8,marginTop:10}}>{links.length===0?<div style={{color:"#8f9ab0"}}>Связей пока нет.</div>:links.map(l=><div key={l.id} style={{display:"flex",justifyContent:"space-between",gap:10,padding:10,border:"1px solid #303747",borderRadius:10}}><span>{l.from_record_id===selected.id?"→":"←"} {nameOf(l.from_record_id===selected.id?l.to_record_id:l.from_record_id)}</span><button disabled={busy} onClick={()=>removeLink(l.id)} style={danger}>Удалить</button></div>)}</div></>}</div>
   <div style={{display:"flex",gap:8,marginTop:14}}><button onClick={()=>startEdit(selected)} style={button}>Изменить</button><button onClick={()=>remove(selected.id)} style={danger}>Удалить</button></div>{error&&<div style={{color:"#ffb4b4",marginTop:10}}>{error}</div>}</div>}
  <div style={{padding:20,border:"1px solid #303747",borderRadius:16}}><h2 style={{marginTop:0}}>{editing?"Редактирование записи":"Новая запись"}</h2><p style={{color:"#8f9ab0",fontSize:13}}>{editing?"Измените данные и сохраните запись.":"Заполните поля сущности и сохраните бизнес-запись."}</p><div style={{display:"grid",gap:12,maxWidth:720}}>
   {statuses.length>0&&<label style={{display:"grid",gap:6,color:"#aab2c3"}}>Статус<select value={statusId} onChange={e=>setStatusId(e.target.value)} style={input}><option value="">Без статуса</option>{statuses.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
   {fields.map(f=><label key={f.id} style={{display:"grid",gap:6,color:"#aab2c3"}}>{f.name}{f.required?" *":""}{f.field_type==="long_text"?<textarea value={data[f.key]??""} onChange={e=>setValue(f.key,e.target.value)} style={input} rows={4}/>:f.field_type==="boolean"?<input type="checkbox" checked={!!data[f.key]} onChange={e=>setValue(f.key,e.target.checked)} style={{width:18,height:18}}/>:f.field_type==="select"?<select value={data[f.key]??""} onChange={e=>setValue(f.key,e.target.value)} style={input}><option value="">Выберите…</option>{(f.config?.options??[]).map((o:any)=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>:<input type={inputType(f.field_type)} value={normalizeValue(f,data[f.key])} onChange={e=>setValue(f.key,f.field_type==="number"||f.field_type==="money"||f.field_type==="currency"?(e.target.value===""?"":Number(e.target.value)):e.target.value)} style={input} placeholder={f.key}/>}</label>)}
   <div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={busy} onClick={save} style={button}>{busy?"Сохраняем…":editing?"Сохранить изменения":"Создать запись"}</button>{editing&&<button disabled={busy} onClick={reset} style={secondary}>Отмена</button>}</div>{error&&<div style={{color:"#ffb4b4"}}>{error}</div>}
  </div></div>
  <div style={{padding:20,border:"1px solid #303747",borderRadius:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>Записи</h2><div style={{color:"#8f9ab0",fontSize:13}}>Показано: {filtered.length} из {initialRecords.length}</div></div></div><div style={{display:"grid",gridTemplateColumns:"minmax(220px,2fr) minmax(150px,1fr) minmax(150px,1fr) auto",gap:8,marginTop:14}}><input style={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск по записям…"/><select style={input} value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="">Все статусы</option>{statuses.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select style={input} value={sortKey} onChange={e=>setSortKey(e.target.value)}><option value="updated">По изменению</option><option value="created">По дате создания</option>{fields.slice(0,8).map(f=><option key={f.id} value={f.key}>По полю: {f.name}</option>)}</select><button style={secondary} onClick={()=>setDesc(v=>!v)}>{desc?"↓ Новые":"↑ Старые"}</button></div>
   {filtered.length===0?<div style={{padding:"24px 0",color:"#8f9ab0"}}>{initialRecords.length===0?"Записей пока нет. Создайте первую запись выше.":"По заданным условиям записи не найдены."}</div>:<div style={{display:"grid",gap:10,marginTop:14}}>{filtered.map(r=><article key={r.id} style={{border:"1px solid #303747",borderRadius:12,padding:14,background:"#121620"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div style={{cursor:"pointer"}} onClick={()=>openDetails(r)}><strong>{fields[0]?String(r.data?.[fields[0].key]??"Без названия"):"Запись"}</strong>{r.status_id&&<span style={{marginLeft:8,color:"#aab2c3"}}>{statuses.find(s=>s.id===r.status_id)?.name??"Статус"}</span>}<div style={{fontSize:12,color:"#737e94",marginTop:4}}>Изменено: {new Date(r.updated_at).toLocaleString("ru-RU")}</div></div><div style={{display:"flex",gap:8}}><button disabled={busy} onClick={()=>openDetails(r)} style={secondary}>Открыть карточку</button><button disabled={busy} onClick={()=>startEdit(r)} style={secondary}>Изменить</button><button disabled={busy} onClick={()=>remove(r.id)} style={danger}>Удалить</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8,marginTop:12}}>{fields.slice(0,6).map(f=><div key={f.id} style={{fontSize:13,color:"#aab2c3"}}><span style={{color:"#737e94"}}>{f.name}: </span>{f.field_type==="boolean"?(r.data?.[f.key]?"Да":"Нет"):String(r.data?.[f.key]??"—")}</div>)}</div></article>)}</div>}
  </div>
 </section>
}
const input={padding:11,borderRadius:10,border:"1px solid #303747",background:"#121620",color:"white",width:"100%",boxSizing:"border-box" as const};
const button={width:"fit-content",padding:"11px 16px",borderRadius:10,fontWeight:700};
const secondary={padding:"9px 13px",borderRadius:9,fontWeight:600};
const danger={padding:"9px 13px",borderRadius:9,fontWeight:600,color:"#ffb4b4"};
