"use client";
import {FormEvent,useEffect,useState} from "react";
type Message={role:"user"|"assistant";text:string};
type Model={id:string;name:string;provider:string;model:string;enabled:boolean;is_default:boolean;has_api_key?:boolean};
export default function AiChat({workspaceId,workspaceName}:{workspaceId:string;workspaceName:string}){
const[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[models,setModels]=useState<Model[]>([]),[selected,setSelected]=useState("platform");
useEffect(()=>{fetch("/api/ai/models",{cache:"no-store"}).then(r=>r.json()).then(j=>setModels(Array.isArray(j.items)?j.items:[])).catch(()=>{})},[]);
async function send(e?:FormEvent){e?.preventDefault();const text=input.trim();if(!text||busy)return;setInput("");setError("");setMessages(p=>[...p,{role:"user",text}]);setBusy(true);try{const body:any={workspaceId,message:text,system:"Ты AI-помощник платформы UB OS-RUS. Отвечай на русском языке. Пользователь работает в бизнес-системе «"+workspaceName+"». Не проси API-ключи и не раскрывай внутренние идентификаторы моделей. Помогай пользоваться системой и решать бизнес-задачи. Если действие пока невозможно выполнить напрямую, честно объясни это."};if(selected!=="platform")body.modelId=selected;const r=await fetch("/api/ai/command",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||j.error||"AI временно недоступен");setMessages(p=>[...p,{role:"assistant",text:j.text||"AI не вернул текстовый ответ."}]);}catch(err){const m=err instanceof Error?err.message:"Не удалось получить ответ AI";setError(m);setMessages(p=>[...p,{role:"assistant",text:"Не удалось получить ответ. Попробуйте ещё раз."}]);}finally{setBusy(false)}}
return <main style={{minHeight:"calc(100vh - 57px)",background:"#080c13",color:"#eef2ff"}}><div style={{maxWidth:1000,margin:"0 auto",padding:"26px 16px 42px"}}><header style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><div style={{fontSize:12,letterSpacing:".14em",color:"#7dd3c7"}}>UB OS-RUS · AI</div><h1 style={{margin:"7px 0"}}>AI-помощник</h1><p style={{margin:0,color:"#9ea8ba"}}>AI платформы и ваши собственные подключённые модели.</p></div><a href="/app/ai/models" style={linkStyle}>⚙️ Мои AI-модели</a></header><section style={{marginTop:18,border:"1px solid #293244",borderRadius:18,background:"#101621",overflow:"hidden"}}><div style={{padding:"12px 16px",borderBottom:"1px solid #293244",display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><span style={{fontWeight:700}}>🤖 AI-помощник</span><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy} style={selectStyle}><option value="platform">AI платформы — автоматически</option>{models.filter(x=>x.enabled).map(x=><option key={x.id} value={x.id}>Моя модель: {x.name} ({x.provider})</option>)}</select></div><div style={{padding:"8px 16px",fontSize:12,color:"#7dd3c7"}}>{selected==="platform"?"Используется модель платформы":"Используется ваша подключённая модель"}</div><div style={{minHeight:420,maxHeight:"58vh",overflowY:"auto",padding:16}}>{messages.length===0?<div style={{maxWidth:650,margin:"70px auto",textAlign:"center",color:"#9ea8ba"}}><div style={{fontSize:42}}>🤖</div><h2 style={{color:"#eef2ff"}}>Чем помочь?</h2><p>Выберите AI платформы или свою модель и задайте вопрос.</p><div style={{display:"flex",gap:8,justifyContent:"center",flexWrap:"wrap",marginTop:18}}>{["Как настроить бизнес?","Какие модули у меня активны?","Как создать клиента?"].map(x=><button key={x} onClick={()=>setInput(x)} style={suggestion}>{x}</button>)}</div></div>:messages.map((m,i)=><div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start",marginBottom:12}}><div style={{maxWidth:"82%",padding:"11px 14px",borderRadius:14,background:m.role==="user"?"#16343a":"#18202d",border:"1px solid "+(m.role==="user"?"#285b57":"#293244"),whiteSpace:"pre-wrap",lineHeight:1.5}}>{m.text}</div></div>)}{busy&&<div style={{color:"#8f9bad",fontSize:13}}>AI обрабатывает запрос…</div>}</div><form onSubmit={send} style={{padding:12,borderTop:"1px solid #293244",display:"flex",gap:8}}><input value={input} onChange={e=>setInput(e.target.value)} disabled={busy} placeholder="Напишите, что нужно сделать…" style={inputStyle}/><button disabled={busy||!input.trim()} style={sendButton}>{busy?"…":"Отправить"}</button></form></section>{error&&<div style={{marginTop:10,color:"#ffb5bd",fontSize:13}}>⚠️ {error}</div>}<div style={{marginTop:12,fontSize:12,color:"#657287"}}>Ваши API-ключи хранятся зашифрованно и не показываются после сохранения.</div></div></main>}
const inputStyle={flex:1,minWidth:0,padding:"12px 13px",borderRadius:11,border:"1px solid #374258",background:"#080c13",color:"#fff"};const sendButton={padding:"11px 15px",borderRadius:11,border:"1px solid #3b5264",background:"#16343a",color:"#fff",cursor:"pointer"};const suggestion={padding:"9px 11px",borderRadius:10,border:"1px solid #344254",background:"#0b131c",color:"#cbd5e1",cursor:"pointer"};const linkStyle={padding:"9px 12px",border:"1px solid #2d3949",borderRadius:10,color:"#cbd5e1",textDecoration:"none"};const selectStyle={maxWidth:"100%",padding:"9px 11px",borderRadius:10,border:"1px solid #374258",background:"#080c13",color:"#eef2ff"};
