import Link from "next/link";
import { getWorkspaceContext } from "@/lib/workspace";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import SbpBindButton from "./sbp-bind-button";

const MODULE_META:Record<string,{icon:string;name:string}>={
 crm:{icon:"👥",name:"Клиенты и CRM"},documents:{icon:"📄",name:"Документы"},employees:{icon:"👤",name:"Сотрудники"},finance:{icon:"💰",name:"Финансы"},inventory:{icon:"📦",name:"Склад"},products:{icon:"🛍️",name:"Товары"},projects:{icon:"📋",name:"Проекты"},reports:{icon:"📊",name:"Отчёты"},sales:{icon:"💳",name:"Продажи"},services:{icon:"🛠️",name:"Услуги"},support:{icon:"🎧",name:"Поддержка"}
};

export default async function AppPage(){
 const context=await getWorkspaceContext();
 if(!context?.membership||!context.activeWorkspace)return <main style={shell}><div style={card}><h1>UB OS-RUS</h1><p>Нет активного Workspace.</p><Link href="/onboarding">Настроить рабочее пространство →</Link></div></main>;
 const workspace=context.activeWorkspace;const supabase=await createSupabaseServerClient();
 const {data:entities}=await supabase.from("entity_definitions").select("id,key,name,description").eq("workspace_id",workspace.id).order("name");
 const {data:subscription}=await supabase.from("subscriptions").select("status,trial_ends_at,current_period_end,external_payment_method_id,subscription_plans(name,price_monthly)").eq("organization_id",context.membership.organization_id).maybeSingle();
 const {data:installed}=await supabase.from("workspace_modules").select("module_id").eq("workspace_id",workspace.id).eq("enabled",true);
 const moduleIds=(installed??[]).map((m:any)=>m.module_id).filter(Boolean);
 const {data:defs}=moduleIds.length?await supabase.from("module_definitions").select("id,key,name").in("id",moduleIds):{data:[]};
 const plan=Array.isArray(subscription?.subscription_plans)?subscription.subscription_plans[0]:subscription?.subscription_plans;
 const trialDays=subscription?.trial_ends_at?Math.max(0,Math.ceil((new Date(subscription.trial_ends_at).getTime()-Date.now())/86400000)):null;
 return <main style={shell}><div style={{maxWidth:1180,margin:"0 auto",padding:"28px 16px 48px"}}>
  <section style={{...card,background:"linear-gradient(135deg,#111827,#0d1720)",borderColor:"#26384a"}}><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={eyebrow}>UNIVERSAL BUSINESS OS</div><h1 style={{fontSize:"clamp(28px,5vw,44px)",margin:"8px 0"}}>{workspace.name}</h1><p style={{margin:0,color:"#9ea8ba"}}>Ваш рабочий центр управления бизнесом.</p></div>{subscription&&<div style={planBox}><div style={small}>ТАРИФ</div><strong>{plan?.name??"Тариф"}</strong><div style={{marginTop:5,fontSize:13,color:"#9ea8ba"}}>{subscription.status==="trialing"?"Пробный период · "+trialDays+" дн.":subscription.status==="active"?"Подписка активна":"Статус: "+subscription.status}</div></div>}</div><div style={quickGrid}><Quick href="/app/builder" title="Конструктор" text="Сущности, поля, статусы и процессы"/><Quick href="/app/ai-models" title="🤖 AI-модели" text="Платформенные и собственные модели"/><Quick href="/app/setup" title="Настройка" text="Модули и отраслевой профиль"/></div></section>
  {subscription&&<section id="subscription" style={{...card,marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 5px",fontSize:20}}>Подписка и доступ</h2><div style={{color:"#9ea8ba"}}>{subscription.status==="trialing"?"Пробный период":subscription.status==="active"?"Активная подписка":"Статус: "+subscription.status} · {plan?.name??"—"}</div></div>{!subscription.external_payment_method_id&&<SbpBindButton/>}</div></section>}
  <section style={{marginTop:26}}><h2 style={{margin:"0 0 5px"}}>Рабочие модули</h2><p style={{margin:0,color:"#8f9bad"}}>Активно: {defs?.length??0}</p><div style={moduleGrid}>{(defs??[]).map((m:any)=>{const meta=MODULE_META[m.key]??{icon:"◈",name:m.name??m.key};return <Link key={m.id} href={"/app/modules/"+encodeURIComponent(m.key)} style={moduleCard}><span style={{fontSize:28}}>{meta.icon}</span><strong>{meta.name}</strong><span style={moduleLink}>Открыть →</span></Link>})}</div></section>
  <section style={{marginTop:26}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 5px"}}>Ваши бизнес-объекты</h2><p style={{margin:0,color:"#8f9bad"}}>{entities?.length??0} настроено в текущем Workspace</p></div><Link href="/app/builder" style={action}>+ Создать объект</Link></div><div style={entityGrid}>{(entities??[]).map((entity:any)=><Link key={entity.id} href={"/app/builder/"+entity.id} style={{...card,textDecoration:"none",color:"inherit"}}><strong style={{fontSize:18}}>{entity.name}</strong><div style={{color:"#7f8ca1",marginTop:6}}>{entity.key}</div>{entity.description&&<p style={{color:"#9ea8ba",lineHeight:1.5}}>{entity.description}</p>}<div style={moduleLink}>Открыть →</div></Link>)}</div></section>
 </div></main>
}
function Quick({href,title,text}:{href:string,title:string,text:string}){return <Link href={href} style={quickCard}><strong>{title}</strong><div style={small}>{text}</div></Link>}
const shell={minHeight:"calc(100vh - 57px)",fontFamily:"system-ui"};const card={padding:20,border:"1px solid #293244",borderRadius:18,background:"#101621",boxSizing:"border-box" as const};const eyebrow={fontSize:12,color:"#7dd3c7",letterSpacing:".12em"};const small={fontSize:12,color:"#8f9bad"};const planBox={minWidth:190,padding:14,border:"1px solid #2c3b4d",borderRadius:14,background:"#0a1119"};const quickGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:22};const quickCard={padding:15,border:"1px solid #2a3a49",borderRadius:14,background:"#0b131c",textDecoration:"none",color:"#fff"};const moduleGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,marginTop:14};const moduleCard={display:"grid",gap:7,padding:16,border:"1px solid #29384a",borderRadius:15,background:"#101621",textDecoration:"none",color:"#fff"};const moduleLink={marginTop:7,color:"#7dd3c7",fontSize:13};const entityGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14,marginTop:14};const action={display:"inline-block",padding:"9px 12px",borderRadius:10,border:"1px solid #35515d",background:"#10282d",color:"#d8fff7",textDecoration:"none",fontSize:13};
