"use client";
import {useEffect,useState} from "react";
type M={id:string;name:string;provider:string;model:string;base_url:string|null;role:string;enabled:boolean;priority:number;has_api_key:boolean};
const roles=[["primary","Основная"],["fallback","Резервная"],["general","Общая"],["analytics","Аналитика"],["agent","Агенты"]];
const providers=["openai","openrouter","groq","gemini","anthropic","ollama","custom"];
export default function AdminAiModels(){
 const [items,setItems]=useState<M[]>([]); const [f,setF]=useState({name:"",provider:"openrouter",model:"",baseUrl:"",apiKey:"",role:"general",priority:"100"}); const [msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/admin/ai-models");const j=await r.json();if(r.ok)setItems(j.items||[]);else setMsg(j.error||"Ошибка")}
 useEffect(()=>{load()},[]);
 async function save(){setMsg("");const r=await fetch("/api/admin/ai-models",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...f,priority:Number(f.priority)||100})});const j=await r.json();if(r.ok){setMsg("Модель добавлена");setF({...f,name:"",model:"",apiKey:""});load()}else setMsg(j.error||"Ошибка")}
 async function toggle(m:M){const r=await fetch("/api/admin/ai-models",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...m,baseUrl:m.base_url||"",apiKey:"",config:{}})});if(r.ok)load();else{const j=await r.json();setMsg(j.error||"Ошибка")}}
 async function del(id:string){if(!confirm("Удалить модель из платформенного AI Core?"))return;const r=await fetch("/api/admin/ai-models?id="+id,{method:"DELETE"});if(r.ok)load();else{const j=await r.json();setMsg(j.error||"Ошибка")}}
 return <main style={{maxWidth:1200,margin:"0 auto",padding:32,fontFamily:"system-ui"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:11,letterSpacing:2,opacity:.5}}>AI CORE / MODEL CONTROL CENTER</div><h1>Системные AI-модели</h1><p style={{opacity:.65}}>Модели, которыми управляет администратор платформы. Ключи хранятся зашифрованно и не выводятся в списке.</p></div><a href="/admin/ai">← AI Core</a></div>
 <section style={{marginTop:25,padding:20,border:"1px solid #2b3444",borderRadius:18}}><h2>Добавить модель</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:12}}>{([["name","Название"],["model","Model ID"],["baseUrl","Base URL"],["apiKey","API key"]] as Array<[keyof typeof f,string]>).map(([k,l])=><label key={k}>{l}<input type={k==="apiKey"?"password":"text"} value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})} style={input}/></label>)}<label>Провайдер<select value={f.provider} onChange={e=>setF({...f,provider:e.target.value})} style={input}>{providers.map(x=><option key={x}>{x}</option>)}</select></label><label>Роль<select value={f.role} onChange={e=>setF({...f,role:e.target.value})} style={input}>{roles.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Приоритет<input value={f.priority} onChange={e=>setF({...f,priority:e.target.value})} style={input}/></label></div><button onClick={save} style={button}>+ Добавить в AI Core</button>{msg&&<p>{msg}</p>}</section>
 <section style={{marginTop:25}}><h2>Реестр моделей</h2><div style={{display:"grid",gap:12}}>{items.map(m=><article key={m.id} style={{padding:18,border:"1px solid #283143",borderRadius:16,display:"flex",justifyContent:"space-between",gap:15,flexWrap:"wrap"}}><div><div style={{fontSize:10,letterSpacing:1.5,opacity:.5}}>{m.provider.toUpperCase()} · {m.role.toUpperCase()} · P{m.priority}</div><h3>{m.name}</h3><code>{m.model}</code><div style={{fontSize:12,opacity:.6,marginTop:7}}>{m.has_api_key?"🔐 API key сохранён":"○ без ключа"} {m.base_url&&" · "+m.base_url}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><button onClick={()=>toggle(m)} style={button}>{m.enabled?"Выключить":"Включить"}</button><button onClick={()=>del(m.id)} style={{...button,background:"#32171b"}}>Удалить</button></div></article>)}{!items.length&&<div style={{padding:25,border:"1px dashed #394354",borderRadius:15,opacity:.6}}>Системные модели ещё не добавлены.</div>}</div></section></main>}
const input={display:"block",width:"100%",boxSizing:"border-box" as const,padding:10,marginTop:6,border:"1px solid #aeb6c6",borderRadius:9};const button={padding:"10px 14px",border:"0",borderRadius:9,background:"#111827",color:"#fff",cursor:"pointer"};
