"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
type Module={key:string;name:string;description:string|null};
export default function SetupWizard({workspace,modules,installed,recommended,industryName}:{workspace:{id:string;name:string};modules:Module[];installed:any[];recommended:string[];industryName:string}){
 const router=useRouter();const installedKeys=useMemo(()=>new Set(installed.map((x:any)=>x?.module_definitions?.key).filter(Boolean)),[installed]);
 const [selected,setSelected]=useState<Set<string>>(()=>new Set(modules.filter(m=>recommended.includes(m.key)||installedKeys.has(m.key)).map(m=>m.key)));
 const [step,setStep]=useState(1);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const toggle=(key:string)=>setSelected(p=>{const n=new Set(p);n.has(key)?n.delete(key):n.add(key);return n});
 async function finish(){setBusy(true);setError("");try{const r=await fetch("/api/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspaceId:workspace.id,modules:[...selected]})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||"Не удалось настроить систему.");setBusy(false);return}router.push("/app?launched=1");router.refresh()}catch{setError("Не удалось связаться с сервером.");setBusy(false)}}
 return <main style={{minHeight:"100vh",background:"#090c12",color:"#f7f8fa",padding:"28px 18px",fontFamily:"system-ui"}}><div style={{maxWidth:1000,margin:"0 auto"}}>
  <div style={{fontSize:12,letterSpacing:".14em",color:"#8793aa"}}>UB OS-RUS · МАСТЕР НАСТРОЙКИ</div>
  <h1 style={{fontSize:"clamp(34px,6vw,58px)",lineHeight:1.03,margin:"12px 0"}}>Настроим систему под ваш бизнес.</h1>
  <p style={{maxWidth:720,color:"#aab2c3",fontSize:17,lineHeight:1.55}}>Бизнес <strong style={{color:"#fff"}}>{workspace.name}</strong> создан. Выберите рабочие модули для направления <strong style={{color:"#fff"}}>{industryName}</strong>.</p>
  <div style={{display:"flex",gap:8,margin:"28px 0",flexWrap:"wrap"}}>{[["1","Профиль"],["2","Модули"],["3","Запуск"]].map(([n,l])=><div key={n} style={{padding:"9px 13px",borderRadius:999,border:"1px solid "+(Number(n)===step?"#7889ff":"#303747"),background:Number(n)===step?"#1d2540":"#111620",color:Number(n)===step?"#fff":"#8f9ab0"}}>{n} · {l}</div>)}</div>
  {step===1&&<section style={{padding:24,border:"1px solid #293142",borderRadius:22,background:"#111620"}}><h2 style={{marginTop:0}}>Профиль бизнеса</h2><div style={{display:"grid",gap:12,color:"#b8c0cf"}}><div><span style={{color:"#7f8ba2"}}>Рабочее пространство</span><br/><strong style={{fontSize:20,color:"#fff"}}>{workspace.name}</strong></div><div><span style={{color:"#7f8ba2"}}>Направление</span><br/><strong style={{color:"#fff"}}>{industryName}</strong></div><div><span style={{color:"#7f8ba2"}}>Статус</span><br/><span style={{color:"#9fe3b0"}}>✓ Бизнес создан и готов к настройке</span></div></div><button onClick={()=>setStep(2)} style={{marginTop:24,padding:"13px 20px",borderRadius:12,border:0,fontWeight:800}}>Далее → Модули</button></section>}
  {step===2&&<section><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}>{modules.map(m=>{const on=selected.has(m.key),rec=recommended.includes(m.key);return <button key={m.key} onClick={()=>toggle(m.key)} style={{textAlign:"left",padding:18,borderRadius:18,border:"1px solid "+(on?"#7182ff":"#303747"),background:on?"#18203a":"#111620",color:"#fff",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><strong>{m.name}</strong><span>{on?"✓":"+"}</span></div><div style={{marginTop:8,color:"#929caf",fontSize:13,lineHeight:1.45}}>{m.description}</div>{rec&&<div style={{marginTop:12,fontSize:11,color:"#aab6ff"}}>Рекомендуется для вашей отрасли</div>}</button>})}</div>{error&&<div style={{marginTop:16,padding:13,border:"1px solid #693a3a",borderRadius:12,color:"#ffb4b4"}}>{error}</div>}<div style={{display:"flex",gap:10,marginTop:20,flexWrap:"wrap"}}><button onClick={()=>setStep(1)} style={{padding:"13px 18px",borderRadius:12,border:"1px solid #303747",background:"#111620",color:"#fff"}}>← Назад</button><button onClick={()=>{if(selected.size){setError("");setStep(3)}else setError("Выберите хотя бы один модуль.")}} style={{padding:"13px 20px",borderRadius:12,border:0,fontWeight:800}}>Далее → Запуск</button></div></section>}
  {step===3&&<section style={{padding:24,border:"1px solid #293142",borderRadius:22,background:"#111620"}}><h2 style={{marginTop:0}}>Система готова к запуску</h2><p style={{color:"#aab2c3"}}>Будет включено модулей: <strong style={{color:"#fff"}}>{selected.size}</strong></p><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"18px 0"}}>{modules.filter(m=>selected.has(m.key)).map(m=><span key={m.key} style={{padding:"8px 11px",borderRadius:999,background:"#1b2231",color:"#dbe0ea"}}>{m.name}</span>)}</div><p style={{color:"#8f9ab0",fontSize:13}}>После запуска вы попадёте в рабочий кабинет. Модули можно будет расширять и настраивать в Конструкторе бизнеса.</p>{error&&<div style={{marginBottom:14,padding:13,border:"1px solid #693a3a",borderRadius:12,color:"#ffb4b4"}}>{error}</div>}<div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button disabled={busy} onClick={()=>setStep(2)} style={{padding:"13px 18px",borderRadius:12,border:"1px solid #303747",background:"#111620",color:"#fff"}}>← Изменить</button><button disabled={busy} onClick={finish} style={{padding:"13px 22px",borderRadius:12,border:0,fontWeight:800}}>{busy?"Запускаем систему…":"🚀 Запустить систему"}</button></div></section>}
 </div></main>
}