"use client";
import {FormEvent,useEffect,useState} from "react";
type Model={id:string;name:string;provider:string;model:string;base_url?:string|null;enabled:boolean;is_default:boolean;has_api_key?:boolean};
export default function ModelsPage(){
const[items,setItems]=useState<Model[]>([]),[name,setName]=useState(""),[provider,setProvider]=useState("openrouter"),[model,setModel]=useState(""),[baseUrl,setBaseUrl]=useState(""),[apiKey,setApiKey]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function load(){const r=await fetch("/api/ai/models",{cache:"no-store"});const j=await r.json().catch(()=>({}));if(r.ok)setItems(j.items||[]);}
useEffect(()=>{load().catch(()=>{})},[]);
async function add(e:FormEvent){e.preventDefault();if(!name.trim()||!provider||!model.trim()||!apiKey.trim()){setError("Укажите название, провайдера, Model ID и API KEY.");return}setBusy(true);setError("");try{const r=await fetch("/api/ai/models",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,provider,model,baseUrl,apiKey})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Не удалось подключить модель");setName("");setModel("");setBaseUrl("");setApiKey("");await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
async function remove(id:string){if(!confirm("Удалить подключённую модель?"))return;const r=await fetch("/api/ai/models?id="+encodeURIComponent(id),{method:"DELETE"});if(r.ok)await load();}
async function makeDefault(id:string){const r=await fetch("/api/ai/models",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:"default"})});if(r.ok)await load();}
return <main style={{minHeight:"calc(100vh - 57px)",background:"#080c13",color:"#eef2ff"}}><div style={{maxWidth:1000,margin:"0 auto",padding:"26px 16px 42px"}}><a href="/app/ai" style={link}>← К AI-помощнику</a><h1>Мои AI-модели</h1><p style={muted}>Подключайте собственные модели по API KEY. Ключ хранится зашифрованно и не показывается после сохранения.</p><section style={card}><h2>➕ Подключить модель</h2><form onSubmit={add} style={grid}><input placeholder="Название, например Мой Gemini" value={name} onChange={e=>setName(e.target.value)} style={input}/><select value={provider} onChange={e=>setProvider(e.target.value)} style={input}><option value="openrouter">OpenRouter</option><option value="gemini">Google Gemini</option><option value="groq">Groq</option><option value="openai">OpenAI</option><option value="custom">Другой OpenAI-совместимый API</option></select><input placeholder="Model ID" value={model} onChange={e=>setModel(e.target.value)} style={input}/><input placeholder="Base URL — необязательно" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} style={input}/><input type="password" placeholder="API KEY" value={apiKey} onChange={e=>setApiKey(e.target.value)} style={input}/><button disabled={busy} style={button}>{busy?"Подключение…":"Подключить модель"}</button></form>{error&&<p style={{color:"#ffb5bd"}}>⚠️ {error}</p>}</section><section style={card}><h2>Подключённые модели</h2>{items.length===0?<p style={muted}>Пока нет ваших моделей.</p>:items.map(x=><div key={x.id} style={row}><div><b>{x.name}</b><div style={muted}>{x.provider} · {x.model} · {x.has_api_key?"🔐 ключ сохранён":"⚠️ ключ не задан"}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{x.is_default?<span style={badge}>По умолчанию</span>:<button onClick={()=>makeDefault(x.id)} style={small}>Сделать моей основной</button>}<button onClick={()=>remove(x.id)} style={danger}>Удалить</button></div></div>)}</section></div></main>}
const muted={color:"#9ea8ba"},card={marginTop:18,padding:18,border:"1px solid #293244",borderRadius:18,background:"#101621"},grid={display:"grid",gap:10},input={padding:"12px 13px",borderRadius:11,border:"1px solid #374258",background:"#080c13",color:"#fff"},button={padding:"12px",borderRadius:11,border:"1px solid #3b5264",background:"#16343a",color:"#fff"},small={padding:"8px 10px",borderRadius:9,border:"1px solid #344254",background:"#0b131c",color:"#cbd5e1"},danger={...small,color:"#ffb5bd"},badge={padding:"8px 10px",borderRadius:9,border:"1px solid #285b57",color:"#7dd3c7"},link={color:"#cbd5e1",textDecoration:"none"};