"use client";
import {FormEvent,useEffect,useState} from "react";
type Model={id:string;name:string;provider:string;model:string;enabled:boolean;is_default:boolean;has_api_key?:boolean};
export default function ModelsPage(){
const[items,setItems]=useState<Model[]>([]),[name,setName]=useState(""),[provider,setProvider]=useState("openrouter"),[model,setModel]=useState(""),[baseUrl,setBaseUrl]=useState(""),[apiKey,setApiKey]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function load(){const r=await fetch("/api/ai/models",{cache:"no-store"});const j=await r.json().catch(()=>({}));if(r.ok)setItems(Array.isArray(j.items)?j.items:[]);}
useEffect(()=>{load().catch(()=>{})},[]);
async function add(e:FormEvent){e.preventDefault();if(!name.trim()||!provider||!model.trim()||!apiKey.trim()){setError("Укажите название, провайдера, Model ID и API KEY.");return}setBusy(true);setError("");try{const r=await fetch("/api/ai/models",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,provider,model,baseUrl,apiKey})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Не удалось подключить модель");setName("");setModel("");setBaseUrl("");setApiKey("");await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}
async function remove(id:string){if(!window.confirm("Удалить подключённую модель?"))return;const r=await fetch("/api/ai/models?id="+encodeURIComponent(id),{method:"DELETE"});if(r.ok)await load();}
async function makeDefault(id:string){const r=await fetch("/api/ai/models",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:"default"})});if(r.ok)await load();}
const inputStyle={width:"100%",boxSizing:"border-box" as const,padding:"12px 13px",borderRadius:11,border:"1px solid #374258",background:"#080c13",color:"#fff"};
return <main style={{minHeight:"calc(100vh - 57px)",background:"#080c13",color:"#eef2ff"}}><div style={{maxWidth:1000,margin:"0 auto",padding:"26px 16px 42px"}}><a href="/app/ai" style={{color:"#cbd5e1",textDecoration:"none"}}>← К AI-помощнику</a><h1>Мои AI-модели</h1><p style={{color:"#9ea8ba"}}>Подключайте собственные модели по API KEY. Ключ хранится зашифрованно и не показывается после сохранения.</p><section style={{marginTop:18,padding:18,border:"1px solid #293244",borderRadius:18,background:"#101621"}}><h2>➕ Подключить модель</h2><form onSubmit={add} style={{display:"grid",gap:10}}><input placeholder="Название, например Мой Gemini" value={name} onChange={e=>setName(e.target.value)} style={inputStyle}/><select value={provider} onChange={e=>setProvider(e.target.value)} style={inputStyle}><option value="openrouter">OpenRouter</option><option value="gemini">Google Gemini</option><option value="groq">Groq</option><option value="openai">OpenAI</option><option value="custom">Другой OpenAI-совместимый API</option></select><input placeholder="Model ID" value={model} onChange={e=>setModel(e.target.value)} style={inputStyle}/><input placeholder="Base URL — необязательно" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} style={inputStyle}/><input type="password" placeholder="API KEY" value={apiKey} onChange={e=>setApiKey(e.target.value)} style={inputStyle}/><button disabled={busy} style={{padding:"12px",borderRadius:11,border:"1px solid #3b5264",background:"#16343a",color:"#fff"}}>{busy?"Подключение…":"Подключить модель"}</button></form>{error&&<p style={{color:"#ffb5bd"}}>⚠️ {error}</p>}</section><section style={{marginTop:18,padding:18,border:"1px solid #293244",borderRadius:18,background:"#101621"}}><h2>Подключённые модели</h2>{items.length===0?<p style={{color:"#9ea8ba"}}>Пока нет ваших моделей.</p>:items.map(x=><div key={x.id} style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap",padding:"14px 0",borderBottom:"1px solid #293244"}}><div><b>{x.name}</b><div style={{color:"#9ea8ba",marginTop:4}}>{x.provider} · {x.model} · {x.has_api_key?"🔐 ключ сохранён":"⚠️ ключ не задан"}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{x.is_default?<span style={{padding:"8px 10px",borderRadius:9,border:"1px solid #285b57",color:"#7dd3c7"}}>Моя основная</span>:<button onClick={()=>makeDefault(x.id)} style={{padding:"8px 10px",borderRadius:9,border:"1px solid #344254",background:"#0b131c",color:"#cbd5e1"}}>Сделать основной</button>}<button onClick={()=>remove(x.id)} style={{padding:"8px 10px",borderRadius:9,border:"1px solid #344254",background:"#0b131c",color:"#ffb5bd"}}>Удалить</button></div></div>)}</section></div></main>}
