import {NextResponse} from "next/server";
import {createSupabaseServerClient} from "@/lib/supabase/server";
async function admin(){const s=await createSupabaseServerClient();const {data:c}=await s.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid)return null;const {data:p}=await s.from("platform_settings").select("owner_user_id").eq("id",true).maybeSingle();return p?.owner_user_id===uid?{s,uid}:null}
export async function GET(){const a=await admin();if(!a)return NextResponse.json({error:"ADMIN_REQUIRED"},{status:403});const {data,error}=await a.s.from("admin_ai_conversations").select("id,title,created_at,updated_at").order("updated_at",{ascending:false});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({items:data??[]})}
export async function POST(req:Request){const a=await admin();if(!a)return NextResponse.json({error:"ADMIN_REQUIRED"},{status:403});const b=await req.json();let id=b.conversationId as string|undefined;if(!id){const title=String(b.message||"Новый чат").trim().slice(0,60)||"Новый чат";const {data,error}=await a.s.from("admin_ai_conversations").insert({admin_user_id:a.uid,title}).select("id,title,created_at,updated_at").single();if(error)return NextResponse.json({error:error.message},{status:400});id=data.id}
const {error:me}=await a.s.from("admin_ai_messages").insert({conversation_id:id,role:"user",content:String(b.message||"").trim()});if(me)return NextResponse.json({error:me.message},{status:400});
const r=await fetch(new URL("/api/ai/command",req.url),{method:"POST",headers:{"content-type":"application/json",cookie:req.headers.get("cookie")||""},body:JSON.stringify({message:String(b.message||"").trim(),system:"Ты внутренний AI-помощник администратора UB OS-RUS. Отвечай на русском языке. Помогай администратору анализировать и управлять AI Core, моделями платформы, тарифами, пользователями и системой. Не выдумывай результаты действий, которых не выполнял."})});
const j=await r.json().catch(()=>({}));if(!r.ok){return NextResponse.json({error:j.message||j.error||"AI временно недоступен",conversationId:id},{status:r.status})}
const answer=String(j.text||"AI не вернул ответ.");const {error:ae}=await a.s.from("admin_ai_messages").insert({conversation_id:id,role:"assistant",content:answer});if(ae)return NextResponse.json({error:ae.message},{status:400});await a.s.from("admin_ai_conversations").update({updated_at:new Date().toISOString()}).eq("id",id);return NextResponse.json({conversationId:id,text:answer})}
